BINARY_NAME=guduApp

build:
	@go mod vendor
	@echo "Building Gudu..."
	@go build -o tmp/${BINARY_NAME} .
	@echo "Gudu built!"

run: build
	@echo "Starting Gudu..."
	@./tmp/${BINARY_NAME} &
	@echo "Gudu started!"

clean:
	@echo "Cleaning..."
	@go clean
	@rm tmp/${BINARY_NAME}
	@echo "Cleaned!"

test:
	@echo "Testing..."
	@go test ./...
	@echo "Done!"

start: run

stop:
	@echo "Stopping gudu..."
	@-pkill -SIGTERM -f "./tmp/${BINARY_NAME}"
	@echo "Stopped gudu!"

restart: stop start